from .brands import map_brands_table
from .clients import map_clients_table
from .employees import map_employee_table
from .users import map_user_table
from .parts import map_parts_table
from .order_parts import map_order_parts_table
from .orders import map_orders_table
from .works import map_works_table
from .device_types import map_device_types_table
from .payments import map_payments_table
from .devices import map_devices_table
from .error_logs import map_error_logs_table
from .organization import map_organizations_table